export interface Language {
    name: string;
    learning_curve: number;
    syntax_complexity: number;
    logic_complexity: number;
    memory_management_ease: number;
    similarity_to_other_languages: number;
    community_support: number;
    ecosystem: number;
    performance: number;
    distance_from_machine_code: number;
    parameter_strictness: number;
    prevention_of_runtime_bugs: number;
  }
  
export const languages: Language[] = [
    {
      name: "Rust",
      learning_curve: 7,
      syntax_complexity: 7,
      logic_complexity: 7,
      memory_management_ease: 7,
      similarity_to_other_languages: 5,
      community_support: 7,
      ecosystem: 7,
      performance: 9,
      distance_from_machine_code: 1,
      parameter_strictness: 9,
      prevention_of_runtime_bugs: 9,
    },
    {
      name: "C++",
      learning_curve: 8,
      syntax_complexity: 8,
      logic_complexity: 8,
      memory_management_ease: 4,
      similarity_to_other_languages: 4,
      community_support: 7,
      ecosystem: 7,
      performance: 9,
      distance_from_machine_code: 2,
      parameter_strictness: 6,
      prevention_of_runtime_bugs: 6,
    },
    {
      name: "Python",
      learning_curve: 3,
      syntax_complexity: 3,
      logic_complexity: 3,
      memory_management_ease: 5,
      similarity_to_other_languages: 7,
      community_support: 9,
      ecosystem: 8,
      performance: 6,
      distance_from_machine_code: 3,
      parameter_strictness: 5,
      prevention_of_runtime_bugs: 7,
    },
    {
      name: "JavaScript",
      learning_curve: 5,
      syntax_complexity: 4,
      logic_complexity: 4,
      memory_management_ease: 6,
      similarity_to_other_languages: 6,
      community_support: 9,
      ecosystem: 9,
      performance: 7,
      distance_from_machine_code: 4,
      parameter_strictness: 4,
      prevention_of_runtime_bugs: 5,
    },
    {
      name: "Java",
      learning_curve: 6,
      syntax_complexity: 6,
      logic_complexity: 6,
      memory_management_ease: 5,
      similarity_to_other_languages: 5,
      community_support: 8,
      ecosystem: 8,
      performance: 8,
      distance_from_machine_code: 3,
      parameter_strictness: 6,
      prevention_of_runtime_bugs: 6,
    },
    {
      name: "C#",
      learning_curve: 6,
      syntax_complexity: 6,
      logic_complexity: 6,
      memory_management_ease: 5,
      similarity_to_other_languages: 5,
      community_support: 8,
      ecosystem: 8,
      performance: 8,
      distance_from_machine_code: 3,
      parameter_strictness: 6,
      prevention_of_runtime_bugs: 7,
    },
    {
      name: "C",
      learning_curve: 5,
      syntax_complexity: 5,
      logic_complexity: 5,
      memory_management_ease: 4,
      similarity_to_other_languages: 8,
      community_support: 7,
      ecosystem: 6,
      performance: 8,
      distance_from_machine_code: 2,
      parameter_strictness: 3,
      prevention_of_runtime_bugs: 4,
    },
    {
      name: "Swift",
      learning_curve: 5,
      syntax_complexity: 5,
      logic_complexity: 5,
      memory_management_ease: 5,
      similarity_to_other_languages: 6,
      community_support: 8,
      ecosystem: 7,
      performance: 7,
      distance_from_machine_code: 3,
      parameter_strictness: 5,
      prevention_of_runtime_bugs: 6,
    },
    {
      name: "Go",
      learning_curve: 5,
      syntax_complexity: 5,
      logic_complexity: 5,
      memory_management_ease: 5,
      similarity_to_other_languages: 6,
      community_support: 8,
      ecosystem: 8,
      performance: 8,
      distance_from_machine_code: 3,
      parameter_strictness: 7,
      prevention_of_runtime_bugs: 8,
    },
    {
      name: "Ruby",
      learning_curve: 5,
      syntax_complexity: 5,
      logic_complexity: 5,
      memory_management_ease: 5,
      similarity_to_other_languages: 4,
      community_support: 7,
      ecosystem: 6,
      performance: 5,
      distance_from_machine_code: 2,
      parameter_strictness: 3,
      prevention_of_runtime_bugs: 4,
    },
  ];

  