import { Language } from "./languages";

export const programmers: Language[] = [
  {
    name: "Beginner Programmer",
    learning_curve: 2,
    syntax_complexity: 2,
    logic_complexity: 2,
    memory_management_ease: 5,
    similarity_to_other_languages: 8,
    community_support: 9,
    ecosystem: 7,
    performance: 6,
    distance_from_machine_code: 9,
    parameter_strictness: 5,
    prevention_of_runtime_bugs: 5,
  },
  {
    name: "Junior Front-end Developer",
    learning_curve: 3,
    syntax_complexity: 3,
    logic_complexity: 3,
    memory_management_ease: 5,
    similarity_to_other_languages: 8,
    community_support: 9,
    ecosystem: 8,
    performance: 7,
    distance_from_machine_code: 8,
    parameter_strictness: 6,
    prevention_of_runtime_bugs: 6,
  },
  {
    name: "Senior Back-end Developer",
    learning_curve: 4,
    syntax_complexity: 4,
    logic_complexity: 7,
    memory_management_ease: 7,
    similarity_to_other_languages: 7,
    community_support: 8,
    ecosystem: 9,
    performance: 8,
    distance_from_machine_code: 6,
    parameter_strictness: 8,
    prevention_of_runtime_bugs: 8,
  },
  {
    name: "Lead Data Scientist",
    learning_curve: 6,
    syntax_complexity: 5,
    logic_complexity: 9,
    memory_management_ease: 6,
    similarity_to_other_languages: 6,
    community_support: 7,
    ecosystem: 8,
    performance: 9,
    distance_from_machine_code: 7,
    parameter_strictness: 7,
    prevention_of_runtime_bugs: 7,
  },
  {
    name: "Principal Systems Architect",
    learning_curve: 7,
    syntax_complexity: 6,
    logic_complexity: 9,
    memory_management_ease: 8,
    similarity_to_other_languages: 7,
    community_support: 8,
    ecosystem: 10,
    performance: 10,
    distance_from_machine_code: 3,
    parameter_strictness: 9,
    prevention_of_runtime_bugs: 9,
  },
  {
    name: "Systems Programmer",
    learning_curve: 5,
    syntax_complexity: 5,
    logic_complexity: 9,
    memory_management_ease: 9,
    similarity_to_other_languages: 7,
    community_support: 8,
    ecosystem: 10,
    performance: 10,
    distance_from_machine_code: 2,
    parameter_strictness: 9,
    prevention_of_runtime_bugs: 9,
  },
  {
    name: "Web Developer",
    learning_curve: 4,
    syntax_complexity: 4,
    logic_complexity: 4,
    memory_management_ease: 4,
    similarity_to_other_languages: 7,
    community_support: 10,
    ecosystem: 8,
    performance: 8,
    distance_from_machine_code: 5,
    parameter_strictness: 5,
    prevention_of_runtime_bugs: 8,
  },
  {
    name: "Data Scientist",
    learning_curve: 7,
    syntax_complexity: 4,
    logic_complexity: 9,
    memory_management_ease: 5,
    similarity_to_other_languages: 5,
    community_support: 5,
    ecosystem: 7,
    performance: 9,
    distance_from_machine_code: 5,
    parameter_strictness: 5,
    prevention_of_runtime_bugs: 5,
  }
  ];

  